/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alejandro' at '3/24/17 8:19 PM' with Gradle 2.14.1
 *
 * @author alejandro, @date 3/24/17 8:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
